name: 🔄 Sync version with upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "19 18 * * *"
  push:
    paths:
      - .github/workflows/ci/yml
    branches:
      - workflow_test

jobs:
  sync:
    name: 🔄 Sync version with upstream
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Sync version with upstream
        uses: snapcrafters/ci/sync-version@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: workflow_test
          update-script: |
            VERSION=$(
                curl -sL https://api.github.com/repos/zed-industries/zed/releases |
                jq .  | grep tag_name | grep -v pre | head -n 1 | cut -d'"' -f4 | tr -d 'v'
            )
            sed -i 's/^\(version: \).*$/\1'"$VERSION"'/' snap/snapcraft.yaml

      - run: echo $(git diff)
